### ISSUE TITLE
Can't link my account

### ISSUE THREAD

**Issue by mcmyt** [deivuh/DODropletManager-OSX#42]
Hey guys, I can't link my DO's account. Here is the preference window

<img width="521" alt="capture d ecran 2015-11-15 a 20 09 58" src="https://cloud.githubusercontent.com/assets/623186/11170448/e7be1c0a-8bd4-11e5-8c51-c05211b9f3aa.png">

**Comment by deivuh** [comment]
Found the problem, I made a mistake linking the button.

I'll upload the fixed version in a while.
